### ISSUE TITLE
Send broad cast issue on socket server

### ISSUE THREAD

**Issue by jheorge** [darryncampbell/datawedge-websockets-bridge#4]
Hi, I have a problem at the moment to send message through the  socket, when I did the test with the example page that has the triggers of the message in buttons like this
document.getElementById('enablePluginButton').setAttribute("onclick", "sendMessageToServer(msg_input_plugin_enable);");
document.getElementById('disablePluginButton').setAttribute("onclick", "sendMessageToServer(msg_input_plugin_disable);");

works fines but If I try to send the message directly without use the buttons like a triggers, like this:

ws.sendMessageToServer(msg_input_plugin_disable);
alert("some error");
ws.sendMessageToServer(msg_input_plugin_enable);

the instruction of "ws.sendMessageToServer(msg_input_plugin_disable);" pass successfully and stop the  datawedge but the line of code "ws.sendMessageToServer(msg_input_plugin_enable);" goes to the server execute the intent but is not taking in account and nothing happens

someone has any idea about that issue,

regards

**Comment by darryncampbell** [comment]
Just to ask a silly question, sendMessageToServer is not a method of the ws (WebSocket) object, so there is a typo in your question?

**Comment by jheorge** [comment]
Gotcha that method it's on the webpage.html the example that you have in your repo. I'm just using the same name to send message to my socket server that's it
function sendMessageToServer(json_msg)
{
	if (socketClosed)
		init();
	else
	{
		ws.send(JSON.stringify(json_msg));
		//  ws.send("Hello from " + navigator.userAgent);
	}
}

**Comment by darryncampbell** [comment]
Can you please share your test page?

**Comment by jheorge** [comment]
sure right now we are using asp.net . So here is our script

`<script type="text/javascript">

    // RvBarcode socket server properties
    address = "127.0.0.1";
    port = "12345";
    var msg_input_plugin_enable = { "action": " com.symbol.datawedge.api.ACTION_SCANNERINPUTPLUGIN", "extra_key": "com.symbol.datawedge.api.EXTRA_PARAMETER", "extra_value": "ENABLE_PLUGIN" };
    var msg_input_plugin_disable = { "action": "com.symbol.datawedge.api.ACTION_SCANNERINPUTPLUGIN", "extra_key": "com.symbol.datawedge.api.EXTRA_PARAMETER", "extra_value": "DISABLE_PLUGIN" };

    function callRvBarcodePro(errorMessage) {
        socketClosed = true;
        function init() {
            ws = new WebSocket("ws://" + address + ":" + port + "/");
            ws.onmessage = function (event) {
                document.getElementById('socketmessages').innerHTML = event.data + "<BR/>" + document.getElementById('socketmessages').innerHTML;
                console.log(event.data);
            };
            //  In production you would want this to be resiliant against the server being killed by Android, by the user navigating between pages or any other unexpected error related to connection.
            ws.onclose = function () {
                setSocketStatus("Socket closed");
                console.log("Socket closed");
                socketClosed = true;
            };

            ws.onopen = function () {
                setSocketStatus("Socket Connected");
                console.log("Socket Connected");
                socketClosed = false;
                sendMessageToServer();
            };
        }

        function setSocketStatus(message) {
            console.log("Socket Status: " + message);
        }

        function sendMessageToServer() {
                console.log("The message to the socket server ==> " + msg_input_plugin_disable.extra_value);
                ws.send(JSON.stringify(msg_input_plugin_disable));
                alert(errorMessage);
                console.log(errorMessage);
                if (ws.readyState === 1) {
                    console.log("The message to the socket server ==> " + msg_input_plugin_enable.extra_value);
                    ws.send(JSON.stringify(msg_input_plugin_enable));
                }
        }
        init();
    }
</script>`

The call to function "callRvBarcodePro(errorMessage)" it's on server
`    DataWedgescript &=
                       "<script languange='JavaScript'> " &
                       "callRvBarcodePro('" & Message & "'); " &
                       "</script>"`

after the validation of an input

**Comment by darryncampbell** [comment]
I could reproduce the issue with your code above but it looks like the root cause is a space at the beginning of your action name: `var msg_input_plugin_enable = { "action": " com.symbol` (before 'com')

**Comment by jheorge** [comment]
Yep that was the issue "the blank space". Thank you I have been searching some difference on the values but I don't noticed the blank space regards
